---
title: "Analysis Documentation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

## Background
The passage of the ACA in 2010 and the following expansion of Medicaid in many states has resulted in a decrease of the number of Americans without insurance. Insurance coverage is thought to be associated with greater access to primary care. Greater access to primary care should lead to better management of chronic illness indicated by fewer ambulatory care sensitive conditions among other indicators. 

## Research questions
1. Verify that the uninsured rate has decreased since the passage of the ACA and that the decrease was more substantial in states that expanded Medicaid.
      + how should we test this?
2. Verify the association between insurance coverage and access to primary care
      + test at individual and/or state level uning BRFSS questions
3. Look for relationships between greater insurance coverage and better care for the chronically ill
      + decrease in ambulatory care sensitive conditions
      + decrease in stroke, ami, diabetes (still vague about what to test)
      
## Data sources
* BRFSS (years)



ins~ doc
ins~selfcare (diabetes)

checkup
have doctor
self care
preventative care & screenings

ins~screenings

tests:


stratify by age education employment income.





